Update patch set 3
Patch Set 3:

This implementation should be fine.
The only problems are:
 - the field label is automatically added int the web form when it rerouting_codes is set to 'int"
 - the enable/disable button should be removed from the web interface form because they causes issues to the LUA script:
ERROR: app_lua [app_lua_sr.c:991]: lua_sr_pv_seti(): invalid int parameter

Patch-set: 3
Label: Code-Review=0