TT#118659 Switch service mysql->mariadb in ngcp-update-db-schema
After migration to bullseye, ngcp-update-db-schema is broken
inside Docker containers (Jenkins PPA tests):

> https://jenkins.mgm.sipwise.com/job/db-schema-test-db-up-docker/629/console
> ...
> + ngcp-update-db-schema -f
> mysql: unrecognized service
> Error: can't connect to local MariaDB port 3306 using '/etc/mysql/sipwise_extra.cnf'
> ...

Historically, the script ngcp-update-db-schema starts DB (if
it is not running) using the command "service mysql start".

The wrapper 'service' has to use SysV init script as
systemd unit cannot be used inside Docker.
The package mariadb provided backward compatibility symlink
in buster, but it has been removed in bullseye:

> root@11bb38c12e16:/# ls -la /etc/init.d/mysql
> ls: cannot access '/etc/init.d/mysql': No such file or directory
> root@11bb38c12e16:/# ls -la /etc/init.d/mariadb
> -rwxr-xr-x 1 root root 5966 Dec 18 20:25 /etc/init.d/mariadb
> root@11bb38c12e16:/#

The fix here is to use new/proper service name 'mariadb'.

Change-Id: Icf0d663f4a0d5256e1fc403d4fc0f3dd484ebbab